language: cpp

script:
      - git clone --recursive --depth 1 https://github.com/alberthdev/spasm-ng.git
      - cd spasm-ng
      - make NO_APPSIGN=1 -j2
      - cp ./spasm ../spasm
      - cd ..
      - make
